"""
Stage 1 — Entity Overrides.

The LLM frequently misclassifies orthopaedic entities (e.g. "internal fixation" →
Condition instead of Surgical_Procedure). This dictionary provides ground-truth type
overrides keyed by lowercased entity name.

Usage:
    for entity in chunk.entities:
        override = ENTITY_OVERRIDES.get(entity.name.lower())
        if override:
            entity.type = override
"""

# ── Entity-name → correct entity type ──────────────────────────────────────────
# Maintained as a flat dict for O(1) lookup and easy extensibility.
# Keys MUST be lowercase; values MUST match a type in domain.ENTITY_TYPES.

ENTITY_OVERRIDES: dict[str, str] = {

    # ── Anatomical Structures ──────────────────────────────────────────────────
    "femur":                          "Anatomical_Structure",
    "femur neck":                     "Anatomical_Structure",
    "neck of femur":                  "Anatomical_Structure",
    "femoral neck":                   "Anatomical_Structure",
    "femoral head":                   "Anatomical_Structure",
    "femoral shaft":                  "Anatomical_Structure",
    "femoral condyle":                "Anatomical_Structure",
    "tibia":                          "Anatomical_Structure",
    "tibial plateau":                 "Anatomical_Structure",
    "tibial shaft":                   "Anatomical_Structure",
    "fibula":                         "Anatomical_Structure",
    "humerus":                        "Anatomical_Structure",
    "humeral head":                   "Anatomical_Structure",
    "humeral shaft":                  "Anatomical_Structure",
    "radius":                         "Anatomical_Structure",
    "ulna":                           "Anatomical_Structure",
    "scapula":                        "Anatomical_Structure",
    "clavicle":                       "Anatomical_Structure",
    "pelvis":                         "Anatomical_Structure",
    "acetabulum":                     "Anatomical_Structure",
    "patella":                        "Anatomical_Structure",
    "calcaneus":                      "Anatomical_Structure",
    "talus":                          "Anatomical_Structure",
    "metatarsal":                     "Anatomical_Structure",
    "metacarpal":                     "Anatomical_Structure",
    "phalanx":                        "Anatomical_Structure",
    "vertebra":                       "Anatomical_Structure",
    "vertebral body":                 "Anatomical_Structure",
    "cervical spine":                 "Anatomical_Structure",
    "thoracic spine":                 "Anatomical_Structure",
    "lumbar spine":                   "Anatomical_Structure",
    "spine":                          "Anatomical_Structure",
    "sacrum":                         "Anatomical_Structure",
    "coccyx":                         "Anatomical_Structure",
    "intervertebral disc":            "Anatomical_Structure",
    "spinal cord":                    "Anatomical_Structure",
    "meniscus":                       "Anatomical_Structure",
    "medial meniscus":                "Anatomical_Structure",
    "lateral meniscus":               "Anatomical_Structure",
    "anterior cruciate ligament":     "Anatomical_Structure",
    "posterior cruciate ligament":     "Anatomical_Structure",
    "medial collateral ligament":     "Anatomical_Structure",
    "lateral collateral ligament":    "Anatomical_Structure",
    "rotator cuff":                   "Anatomical_Structure",
    "achilles tendon":                "Anatomical_Structure",
    "patellar tendon":                "Anatomical_Structure",
    "quadriceps tendon":              "Anatomical_Structure",
    "labrum":                         "Anatomical_Structure",
    "glenoid":                        "Anatomical_Structure",
    "synovial membrane":              "Anatomical_Structure",
    "articular cartilage":            "Anatomical_Structure",
    "growth plate":                   "Anatomical_Structure",
    "epiphysis":                      "Anatomical_Structure",
    "diaphysis":                      "Anatomical_Structure",
    "metaphysis":                     "Anatomical_Structure",
    "periosteum":                     "Anatomical_Structure",
    "cortical bone":                  "Anatomical_Structure",
    "cancellous bone":                "Anatomical_Structure",
    "bone marrow":                    "Anatomical_Structure",
    "hip joint":                      "Anatomical_Structure",
    "knee joint":                     "Anatomical_Structure",
    "shoulder joint":                 "Anatomical_Structure",
    "elbow joint":                    "Anatomical_Structure",
    "ankle joint":                    "Anatomical_Structure",
    "wrist joint":                    "Anatomical_Structure",
    "sacroiliac joint":               "Anatomical_Structure",
    "acromioclavicular joint":        "Anatomical_Structure",
    "sternoclavicular joint":         "Anatomical_Structure",
    "temporomandibular joint":        "Anatomical_Structure",
    "sciatic nerve":                  "Anatomical_Structure",
    "brachial plexus":                "Anatomical_Structure",
    "radial nerve":                   "Anatomical_Structure",
    "ulnar nerve":                    "Anatomical_Structure",
    "median nerve":                   "Anatomical_Structure",
    "peroneal nerve":                 "Anatomical_Structure",
    "common peroneal nerve":          "Anatomical_Structure",

    # ── Surgical Procedures ────────────────────────────────────────────────────
    "internal fixation":              "Surgical_Procedure",
    "external fixation":              "Surgical_Procedure",
    "open reduction internal fixation": "Surgical_Procedure",
    "open reduction and internal fixation": "Surgical_Procedure",
    "closed reduction":               "Surgical_Procedure",
    "closed reduction and casting":   "Surgical_Procedure",
    "arthroscopy":                    "Surgical_Procedure",
    "arthroplasty":                   "Surgical_Procedure",
    "total hip replacement":          "Surgical_Procedure",
    "total hip arthroplasty":         "Surgical_Procedure",
    "total knee replacement":         "Surgical_Procedure",
    "total knee arthroplasty":        "Surgical_Procedure",
    "hemiarthroplasty":               "Surgical_Procedure",
    "anterior cruciate ligament reconstruction": "Surgical_Procedure",
    "acl reconstruction":             "Surgical_Procedure",
    "tendon repair":                  "Surgical_Procedure",
    "rotator cuff repair":            "Surgical_Procedure",
    "meniscectomy":                   "Surgical_Procedure",
    "osteotomy":                      "Surgical_Procedure",
    "arthrodesis":                    "Surgical_Procedure",
    "spinal fusion":                  "Surgical_Procedure",
    "discectomy":                     "Surgical_Procedure",
    "laminectomy":                    "Surgical_Procedure",
    "decompression":                  "Surgical_Procedure",
    "spinal decompression":           "Surgical_Procedure",
    "amputation":                     "Surgical_Procedure",
    "debridement":                    "Surgical_Procedure",
    "bone grafting":                  "Surgical_Procedure",
    "bone graft":                     "Surgical_Procedure",
    "autograft":                      "Surgical_Procedure",
    "allograft":                      "Surgical_Procedure",
    "fasciotomy":                     "Surgical_Procedure",
    "synovectomy":                    "Surgical_Procedure",
    "excision":                       "Surgical_Procedure",
    "biopsy":                         "Surgical_Procedure",
    "aspiration":                     "Surgical_Procedure",
    "intramedullary nailing":         "Surgical_Procedure",
    "percutaneous pinning":           "Surgical_Procedure",
    "reduction":                      "Surgical_Procedure",
    "manipulation under anesthesia":  "Surgical_Procedure",
    "curettage":                      "Surgical_Procedure",
    "sequestrectomy":                 "Surgical_Procedure",
    "saucerization":                  "Surgical_Procedure",

    # ── Treatments (non-surgical) ──────────────────────────────────────────────
    "traction":                       "Treatment",
    "skeletal traction":              "Treatment",
    "skin traction":                  "Treatment",
    "casting":                        "Treatment",
    "cast immobilization":            "Treatment",
    "splinting":                      "Treatment",
    "bracing":                        "Treatment",
    "immobilization":                 "Treatment",
    "closed reduction and immobilization": "Treatment",
    "rest ice compression elevation": "Treatment",
    "chemotherapy":                   "Treatment",
    "radiotherapy":                   "Treatment",
    "radiation therapy":              "Treatment",
    "conservative management":        "Treatment",
    "conservative treatment":         "Treatment",
    "manipulation":                   "Treatment",
    "injection":                      "Treatment",
    "corticosteroid injection":       "Treatment",
    "steroid injection":              "Treatment",
    "platelet rich plasma":           "Treatment",

    # ── Implants ───────────────────────────────────────────────────────────────
    "plate":                          "Implant",
    "screw":                          "Implant",
    "intramedullary nail":            "Implant",
    "dynamic hip screw":              "Implant",
    "dynamic compression plate":      "Implant",
    "locking plate":                  "Implant",
    "k-wire":                         "Implant",
    "kirschner wire":                 "Implant",
    "steinmann pin":                  "Implant",
    "prosthesis":                     "Implant",
    "bone cement":                    "Implant",
    "polymethylmethacrylate":         "Implant",
    "external fixator":               "Implant",
    "ilizarov fixator":               "Implant",
    "rush nail":                      "Implant",
    "enders nail":                    "Implant",
    "gamma nail":                     "Implant",
    "tension band wire":              "Implant",

    # ── Medications ────────────────────────────────────────────────────────────
    "nsaid":                          "Medication",
    "non-steroidal anti-inflammatory drug": "Medication",
    "analgesic":                      "Medication",
    "antibiotic":                     "Medication",
    "bisphosphonate":                 "Medication",
    "calcium supplement":             "Medication",
    "vitamin d":                      "Medication",
    "anticoagulant":                  "Medication",
    "corticosteroid":                 "Medication",
    "methotrexate":                   "Medication",
    "disease modifying anti-rheumatic drug": "Medication",
    "opioid":                         "Medication",
    "paracetamol":                    "Medication",
    "acetaminophen":                  "Medication",
    "ibuprofen":                      "Medication",
    "diclofenac":                     "Medication",
    "tetanus toxoid":                 "Medication",
    "enoxaparin":                     "Medication",
    "warfarin":                       "Medication",

    # ── Diagnostic Tests ───────────────────────────────────────────────────────
    "x-ray":                          "Diagnostic_Test",
    "radiograph":                     "Diagnostic_Test",
    "plain radiograph":               "Diagnostic_Test",
    "magnetic resonance imaging":     "Diagnostic_Test",
    "computed tomography":            "Diagnostic_Test",
    "ct scan":                        "Diagnostic_Test",
    "bone scan":                      "Diagnostic_Test",
    "bone scintigraphy":              "Diagnostic_Test",
    "ultrasound":                     "Diagnostic_Test",
    "dual energy x-ray absorptiometry": "Diagnostic_Test",
    "dexa scan":                      "Diagnostic_Test",
    "bone mineral density":           "Diagnostic_Test",
    "electromyography":               "Diagnostic_Test",
    "nerve conduction study":         "Diagnostic_Test",
    "arthrography":                   "Diagnostic_Test",
    "bone biopsy":                    "Diagnostic_Test",
    "blood culture":                  "Diagnostic_Test",
    "erythrocyte sedimentation rate": "Diagnostic_Test",
    "c-reactive protein":             "Diagnostic_Test",
    "complete blood count":           "Diagnostic_Test",
    "alkaline phosphatase":           "Diagnostic_Test",
    "serum calcium":                  "Diagnostic_Test",

    # ── Rehabilitation ─────────────────────────────────────────────────────────
    "physiotherapy":                  "Rehabilitation",
    "physical therapy":               "Rehabilitation",
    "occupational therapy":           "Rehabilitation",
    "gait training":                  "Rehabilitation",
    "range of motion exercises":      "Rehabilitation",
    "quadriceps strengthening":       "Rehabilitation",
    "weight bearing":                 "Rehabilitation",
    "partial weight bearing":         "Rehabilitation",
    "non-weight bearing":             "Rehabilitation",
    "crutch walking":                 "Rehabilitation",
    "continuous passive motion":      "Rehabilitation",
    "isometric exercises":            "Rehabilitation",
    "progressive resistance exercises": "Rehabilitation",

    # ── Symptoms ───────────────────────────────────────────────────────────────
    "pain":                           "Symptom",
    "swelling":                       "Symptom",
    "tenderness":                     "Symptom",
    "stiffness":                      "Symptom",
    "deformity":                      "Symptom",
    "crepitus":                       "Symptom",
    "instability":                    "Symptom",
    "loss of function":               "Symptom",
    "restricted range of motion":     "Symptom",
    "limping":                        "Symptom",
    "muscle wasting":                 "Symptom",
    "numbness":                       "Symptom",
    "weakness":                       "Symptom",
    "locking":                        "Symptom",
    "giving way":                     "Symptom",
    "effusion":                       "Symptom",
    "shortening":                     "Symptom",
    "abnormal mobility":              "Symptom",

    # ── Complications ──────────────────────────────────────────────────────────
    "nonunion":                       "Complication",
    "non-union":                      "Complication",
    "malunion":                       "Complication",
    "delayed union":                  "Complication",
    "avascular necrosis":             "Complication",
    "osteonecrosis":                  "Complication",
    "implant failure":                "Complication",
    "infection":                      "Complication",
    "wound infection":                "Complication",
    "deep vein thrombosis":           "Complication",
    "pulmonary embolism":             "Complication",
    "compartment syndrome":           "Complication",
    "fat embolism":                   "Complication",
    "fat embolism syndrome":          "Complication",
    "refracture":                     "Complication",
    "stiffness":                      "Symptom",  # note: overlaps symptom, symptom wins
    "nerve injury":                   "Complication",
    "vascular injury":                "Complication",
    "volkmann ischemic contracture":  "Complication",
    "myositis ossificans":            "Complication",
    "sudeck atrophy":                 "Complication",
    "complex regional pain syndrome": "Complication",
    "heterotopic ossification":       "Complication",
    "periprosthetic fracture":        "Complication",
    "dislocation":                    "Complication",
    "prosthetic loosening":           "Complication",

    # ── Risk Factors ───────────────────────────────────────────────────────────
    "smoking":                        "Risk_Factor",
    "obesity":                        "Risk_Factor",
    "diabetes mellitus":              "Risk_Factor",
    "osteoporosis":                   "Risk_Factor",
    "advanced age":                   "Risk_Factor",
    "steroid use":                    "Risk_Factor",
    "malnutrition":                   "Risk_Factor",

    # ── Outcomes ───────────────────────────────────────────────────────────────
    "fracture union":                 "Outcome",
    "fracture healing":               "Outcome",
    "bone union":                     "Outcome",
    "functional recovery":            "Outcome",
    "return to activity":             "Outcome",
    "full weight bearing":            "Outcome",
    "radiographic union":             "Outcome",
}
